### ISSUE TITLE
Initial todo list

### ISSUE THREAD

**Issue by alewis729** [alewis729/reddit-posts#1]
## UI Design

![sketch](https://user-images.githubusercontent.com/51219653/116006098-72563e00-a5cf-11eb-80ea-8ea1cd14e59d.png)

## Requirements

- [x] Pagination support
- [x] Saving pictures in the picture gallery
- [x] App state-preservation/restoration
- [x] Indicator of unread/read post (updated status, after post it’s selected)
- [x] Dismiss Post Button (remove the cell from list. Animations required)
- [x] Dismiss All Button (remove all posts. Animations required)
- [x] Support split layout (left side: all posts / right side: detail post)
- [x] Responsive design
- [x] Post should display:
    - [x] Title (at its full length, so take this into account when sizing your cells)
    - [x] Author
    - [x] entry date, following a format like “x hours ago”
    - [x] A thumbnail for those who have a picture.
    - [x] Number of comments
    - [x] Unread status
- [x] Documentation
- [x] Deployment

## Todo list

The following is a list of ordered tasks from highest priority to lowest. I'll possibly change the priority of some tasks while developing, but for now I'll just create the list to have a solid idea of all (or at least most) of the tasks before beginning.

- [x] 1. CRA & code base config
- [x] 2. add deps that I'll use for sure
- [x] 3. routing, `App.tsx`, pages & layout
- [x] 4. store & `getPosts` from Reddit API
- [x] 5. components (`PostsPage`) with usage of API data & complete functionality
- [x] 6. `GalleryPage` & functionality
- [x] 7. Responsiveness
- [x] 8. persist store
- [x] 9. tests
- [x] 10. QA, additional improvements & optimisations?
- [x] Documentation
- [x] Deployment

**Comment by alewis729** [comment]
The tasks mentioned here were completed successfully.
